### PR TITLE
Don't call ApplicationPath during instantiation

### PR DESCRIPTION
**Pull request by SlimJimDodger**
This instantiation call to KSPUtil.ApplicationRootPath fills the deblug mode log file with 100's of megs of bad juju.

Let's move it.

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
You may have a point, but I can't accept this PR.  It's replacing almost the entire file, looks like you may have reformatted it?

Please redo, or I'll just do it myself.  It's a 2 line change, but you have about 500 lines of diffs

Also, were you on 1.7.3 or 1.8.0?

**Comment by linuxgurugamer** [comment]
Actually, I just did the fix in my local repo, so it will be updated when I get to the 1.8 updates.
I still need to know if you had this happen on 1.7.3 or 1.8.0?

**Comment by SlimJimDodger** [comment]
This is on 1.7.3., but the bug has existed since day one on all version.

The diffs you are seeing are just whitespace from tab replacements. I'm assuming git has an option to ignore whitespace changes.

**Comment by linuxgurugamer** [comment]
I really don't care what the differences are.  It's your responsibility to not change every line. Git does, but github does not, and I review these on Github.

The bug will be fixed in the next release

**Pull request closed without merging**
